[package]
name = "repo_author"
version = "0.3.0"
edition = "2024"
description = "add, remove, list project's author.txt"
license = "MIT"

[[bin]]
name = "author"
path = "src/main.rs"

[dependencies]
colored = "2"
inquire = "0.6"
thiserror = "1"
